services:
  api:
    container_name: agendamentos_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 127.0.0.1:${API_PORT:-3000}:3000
    env_file:
      - .env
    networks:
      - agendamentos_network
    depends_on:
     - postgres
  
  postgres:
    container_name: agendamentos_db
    image: postgres:17-alpine
    networks:
      - agendamentos_network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 127.0.0.1:${DB_PORT_EXTERNAL:-5432}:${DB_PORT:-5432}
    volumes:
      - api_db_data:/var/lib/postgresql/data

networks:
  agendamentos_network:
    name: agendamentos_network

volumes:
  api_db_data: